In [1]:
import pandas as pd

In [17]:
t1 = pd.read_csv('IT_wordcloud_contribution.csv')

In [18]:
t2 = pd.read_csv('IT_wordcloud_contribution_idf.csv')

In [19]:
t1['rating_1'] = range(1, len(t1) + 1)

In [20]:
t2['rating_2'] = range(1, len(t2) + 1)

In [21]:
t1.drop('value', axis=1).merge(t2.drop('value', axis=1))

                              word  rating_1  rating_2
0                       consulting         1         2
1                productmanagement         2         1
2              informationsecurity         3        10
3            stakeholdermanagement         4         3
4                            agile         5         6
5                   decisionmaking         6         8
6             businessintelligence         7         4
7                             ssas         8         5
8                          outlook         9         9
9                      datascience        10         7
10                  datamanagement        11        13
11                           visio        12        15
12                      statistics        13        19
13                       marketing        14        16
14                       analytics        15        21
15                      javascript        16        11
16                            unix        17        12
17                       databases        18        20
18                    dataanalysis        19        25
19                      production        20        24
20                             aws        21        26
21                          retail        22        18
22                          oracle        23        27
23                             gis        24        14
24                         pyspark        25        17
25                            ssis        26        22
26                criticalthinking        27        33
27                             sap        28        31
28                    presentation        29        32
29                            perl        30        23
30                      salesforce        31        28
31                             sas        32        34
32                            word        33        30
33                  problemsolving        34        35
34                          matlab        35        29
35                  organizational        36        40
36                  interpretation        37        39
37                             vba        38        36
38                  timemanagement        39        42
39                      leadership        40        43
40               projectmanagement        41        38
41  reimbursementaccessenvironment        42        44
42                           stata        43        45
43                        teamwork        44        49
44                        research        45        46
45                               r        46        47
46                googledatastudio        47        37
47                   visualization        48        50
48                         tableau        49        51
49            quantitativeresearch        50        52
50                        planning        51        53
51                            spss        52        41
52                           excel        53        55
53                   communication        54        54
54                   interpersonal        55        56
55                          python        56        57
56                             sql        57        58
57                       attention        58        48
58                          hadoop        59        59

In [ ]:
Сильно снизились: information security, statistics, analytics, data analysis и другие часто встречающиеся скиллы
Значительно выросли: business intelligence, SSAS, javascript, UNIX, GIS и другие редкие скиллы